sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t samvidocker/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true samvidocker/docker-frontend npm run test
